### ISSUE TITLE
Invalid Visualisation error

### ISSUE THREAD

**Issue by laffeyad** [HighCoordination/trueChart-Menubar4Sense#10]
I'm getting an error with this extension this morning, 'The Visualization was not found on the server: tcmenu' Was working fine yesterday. I'm running the June version of Sense.

**Comment by phucci** [comment]
Same for me:  
'The Visualization was not found on the server: tcmenu' 
Also running "June 2018" version of QlikSense.

**Comment by HighCoordination** [comment]
Hi guys,

please make sure you are using our latest version (v1.3.1) of the menu bar. This can only be obtained via the download link. Here in GitHub we haven't published the latest version (is still v1.3.0).

Link: [Download Menubar](https://www.highcoordination.com/downloads/truechart-menubar)

Only version v1.3.1 supports Qlik Sense June 2018!

Best regards
Stefan
