### ISSUE TITLE
"The Visualization was not found on the server: tcmenu"

### ISSUE THREAD

**Issue by phucci** [HighCoordination/trueChart-Menubar4Sense#11]
Extension looks promising but sadly we can't test it on QlikSense desktop version "June 2018". 
After installation we get error message: "Invalid Visualisation - The Visualization was not found on the server: tcmenu"

**Comment by HighCoordination** [comment]
@phucci 

please make sure you are using our latest version (v1.3.1) of the menu bar. This can only be obtained via the download link. Here in GitHub we haven't published the latest version (is still v1.3.0).

Link: Download Menubar

Only version v1.3.1 supports Qlik Sense June 2018!

Best regards
Stefan
