### ISSUE TITLE
cant install within QS Sept 2017 - Invalid visualisation, and files missing after import

### ISSUE THREAD

**Issue by CarmelleIBI** [HighCoordination/trueChart-Menubar4Sense#12]
Creates invalid visualisation error after downloading the latest version and importing the zip file to QMC. Noted you only see the resources content within the Static content/Extensions/tcmenu folder, instead of a structure that matches the source code here.

thanks

**Comment by CarmelleIBI** [comment]
![folder structure](https://user-images.githubusercontent.com/40570366/42698337-8839e92e-86b5-11e8-85a1-1be587bdff2b.PNG)

**Comment by CarmelleIBI** [comment]
![error 2](https://user-images.githubusercontent.com/40570366/42698450-dbbd7ebc-86b5-11e8-9ddc-aef2c96d20bf.PNG)

**Comment by HighCoordination** [comment]
Hey there,
for some reason all js files (except config.js) are missing... did your virusscanner remove those for some reason? Your folder should look like this:
![image](https://user-images.githubusercontent.com/33869116/43073568-693cfcc4-8e7a-11e8-8622-05dd3c414600.png)
