### ISSUE TITLE
Hover Text Color of Button - June 2018

### ISSUE THREAD

**Issue by GSGMicha** [HighCoordination/trueChart-Menubar4Sense#13]
Hi,
if you set the text-hover color in the **appearance-section** and create a button he does not inherit it. The button itself has no hover color at all.
In the sourcecode he changes the text color of the 
`class="hico-relative ng-scope bg-isolate-scope" ng-if="item.type==='button'"`
but keeps the color in the inherited _button-container_ and _lui-button_ - divs.

Thanks!

**Comment by HighCoordination** [comment]
Hey there,
unfortunately thats a bug which will be fixed in the next release.

Best Regards,
Uwe

**Comment by Mich90R** [comment]
Thank you very much!

**Comment by HighCoordination** [comment]
The bug was fixed with the version v1.3.3
