### ISSUE TITLE
Extension not working with Qlik Sense September 2018 Release

### ISSUE THREAD

**Issue by Mbencheikh** [HighCoordination/trueChart-Menubar4Sense#23]
Extension not working with Qlik Sense September 2018 Release

**Comment by HighCoordination** [comment]
did you download the zip from git? if yes, thats not a working extension, you will have to build the extension with git download.

you can download a build extension @ 
https://www.highcoordination.com/downloads/truechart-menubar/

**Comment by HighCoordination** [comment]
Support for Qlik Sense 2018 was introduced with version v1.3.1 of the menubar. The latest release can be downloaded [here](https://www.highcoordination.com/downloads/truechart-menubar/).
