### ISSUE TITLE
Very slow and memory leak

### ISSUE THREAD

**Issue by imtiazu** [HighCoordination/trueChart-Menubar4Sense#31]
Hi,

There is something seriously wrong with this extension. Performance is terrible and even worse, it's got a huge memory leak. You can replicate this easily, just add a CLEAR button on the menu, press it and watch the Qlik Sense engine grab more and more RAM each time you press the button. Shame as it's a great extension but I won't pay for something which hasn't been QA'd properly.

**Comment by HighCoordination** [comment]
Hi imitiazu,

many thx for your request/feedback. 

In the context of our licensable version, we are continuously working on the improvement and further development of our product menubar, among others. As you can imagine, the regular Qlik Sense updates require constant adjustments. So, therefore, we have been further developed versions for a while now, which, among other things, solve the problem you mentioned. 

So feel free to contact us for a menubar license (info@trueChart.com). 

The complete overview of all menubar releases can be found here: https://kb.truechart.com/wiki/pages/viewpage.action?pageId=30016479.

Here is an overview of which version of menubar supports which version of Qlik Sense: https://kb.truechart.com/wiki/display/tckb/menubar#menubar-QlikSense%C2%AESupport.

Besides, we plan to provide a new version of the menubar here until Qlik World in May 2020.

Best regards 
HICO - Group

**Comment by imtiazu** [comment]
I don’t see anything in your notes which suggests this issue has been fixed. In addition I downloaded the latest trial version already, where I am experiencing such issues.
Overall performance issues for this extension are bad too.
