### ISSUE TITLE
Selection Panel issue with Menubar

### ISSUE THREAD

**Issue by demcug** [HighCoordination/trueChart-Menubar4Sense#35]
Hi All,
with QlikSense **Feb 2023 Patch 2**, i have noticed that the Menubar (**version 1.3.4_204**) cause a issue on Selection Panel.
The panel move down when insert in one sheet the Menubar.
Below a screen where the filter is almost invisible (see the red arrow) 

<img width="960" alt="image" src="https://github.com/HighCoordination/trueChart-Menubar4Sense/assets/138440219/2ce5e9f1-d67d-4e82-9261-f5e55582cc87">

With the previous version of qlik, the component worked well.
Any help?

Thanks and Regards

**Comment by HighCoordination** [comment]
Good Day, 

Thank you for reaching out. 

Unfortunately, version 1.3.4_204 of MENUBAR is not supported on the latest Qlik versions. 

Please get in touch with the TRUECHART team at info@truechart.com for further assistance on pricing and how to get the latest version of MENUBAR that is compatible with the latest Qlik versions. 

Kind Regards, 
The TRUECHART Team
