### ISSUE TITLE
Delete action and order sequentially buttons are outside the margin of the button window

### ISSUE THREAD

**Issue by Kielland** [HighCoordination/trueChart-Menubar4Sense#4]
Hi!

I'm on 1.2.4_176.

Notice that (in the picture below), the delete action and run sequentially buttons are both invisible. I guess they are outside of the margin of the window.

![bilde1](https://user-images.githubusercontent.com/15069116/38809327-71dc600c-4183-11e8-99cd-e7ac1a088859.png)

By the way, thanks for the 1.2.4 update, where you have made it possible to add many dimensions into the same control. I haven't tested it yet, but it's top on my list..

Thx
Tor

**Comment by Kielland** [comment]
Regarding my last comment: I've now tested 26 dimensions from different tables in a large model - works like a charm - no delay.

**Comment by HighCoordination** [comment]
Hey Kielland, 

many thx for your input and feedback. :)

Regarding your issue we will investigate the problem. Unfortunately, we could not find anything at a first quick check. Do you possibly use other extensions that could influence the CSS? If not, would it be helpful if you could send us a demo app with the bug?

Many thanks and many greetings
Stefan

**Comment by Kielland** [comment]
Great, I've emailed you at your corporate mailbox.
Thx
Tor
