### ISSUE TITLE
Notification when library is updated

### ISSUE THREAD

**Issue by Kielland** [HighCoordination/trueChart-Menubar4Sense#5]
Hi guys

I notice that your library is being updated regularly, which is great! This is, without comparison, the best qlik sense extension available. In the latest update (1.3), I'm particularly interested in the "Button Action "Select Value(s)" not working for all field types (numeric vs. text) [HICO-40918]" update.

But I wonder - when you don't commit to Github, there is no way for us (users) to be notified of new versions available for download. How can we get notified?

Thx
Tor

(PS! Looking very much forward to the 'hide' functionality, which will save a lot of screen real estate.)

**Comment by HighCoordination** [comment]
Hey Tor,

how are you? We plan to update the git project today. So you will notified if a new release is created here,

Best regards
Stefan
