### ISSUE TITLE
Date picker OK button doesn't work

### ISSUE THREAD

**Issue by Kielland** [HighCoordination/trueChart-Menubar4Sense#6]
Hi

Thx for the new version. Just wanted to inform that the OK button (with green checkmark) on the date picker doesn't seem to work. So no selection is applied. The Cancel button (red) works ok. I'm on version 3.2.

Thx
Tor

**Comment by HighCoordination** [comment]
Hey Tor,

we're not able to reproduce you problem. Could you send us an app containing the problem to support@highcoordination.de ?

Best Regards,
Uwe
