### ISSUE TITLE
Crash the entire app when large frequency on variable slider

### ISSUE THREAD

**Issue by davidmunoz-dev** [HighCoordination/trueChart-Menubar4Sense#7]
Hello,

I am using QlikSense 3.2 SR3 and when I put a decimal number on a variable slider it crash the entire app.
It could be due because of the large numbers in only one slider or because of decimal value frequency.
Once this number is set it crash qlik sense and it is imposible to open the app again.

Thanks,

**Comment by HighCoordination** [comment]
Hey davidmunoz-dev,

unfortunately decials are not supported for the variable sliders :-(.

Best Regards,
