### ISSUE TITLE
latest version not working on Qlik Sense Desktop June 2018 edition

### ISSUE THREAD

**Issue by omnicomdev** [HighCoordination/trueChart-Menubar4Sense#8]
hello i updated my Qlik Sense Desktop to the latest version ( June 2018 edition) and this extension doesn't appear anymore it has a message " visualization not valid"

**Comment by supriyagangaiah** [comment]
Yes, even i am facing same issue. I have April 2018. It shows Invalid Visualization.

**Comment by URominger** [comment]
hey guys, did you download the zip from github and uploaded it via qmc?
if yes, this won't work. 
you will have to download the zip from 
https://www.highcoordination.com/downloads/truechart-menubar/

Best Regards,
Uwe

**Comment by richprice36** [comment]
I too downloaded from https://www.highcoordination.com/downloads/truechart-menubar/
and still has the same Invalid Visualization.

Error in extension 'extensions/tcmenu/tcmenu': Can not use internal module 'general.services/media-library/media-library'.

Error: Script error for "general.services/media-library/media-library", needed by: extensions/tcmenu/tcmenu

**Comment by omnicomdev** [comment]
no new version is available that fix this problem?

**Comment by URominger** [comment]
They newest version (released) yesterday, supports qliksense june 
https://www.highcoordination.com/downloads/truechart-menubar/

Best Regards,
Uwe

**Comment by URominger** [comment]
@richprice36  for some reason you have "tcmenu/tcmenu/" .. probably you have create an folder inside the folder ;-) 
Please move the extention content one folder upwards (and update to tcmenu 1.3.1) and everything should be working again.

Best Regards,
Uwe
