### ISSUE TITLE
Invalid visulization Error with True Chart Menu Bar on QlikSense June 2018 Version

### ISSUE THREAD

**Issue by roghocom** [HighCoordination/trueChart-Menubar4Sense#9]
Hello, I recently installed QlikSense June 2018 on my Server and then imported the True Chart Menu Bar Extension from GitHub.

I am receiving an error when I try to use the extension in my application.

The Error  is - Invalid Visualization. The visualization was not found on the server:tcmenu

Would you be able to look into it and/or assist me with this issue?

Thank you for your time and support,

**Comment by HighCoordination** [comment]
Hey Roghocom.

the github download is to "build" the extension and won't work if you import the zip from github.
Please download the extension via https://www.highcoordination.com/downloads/truechart-menubar/

(like 100 times said in the readme) 

Best Regards,
Uwe
